Task 12
odevpl/wdp-2308 pull request #17
Opened 2023-08-08 20:28 UTC by Adriannan23

2023-08-11 11:31 UTC, ACCeler94 requested changes
Please look for comments in the review (ProductBox.js)

2023-08-11 11:31 UTC, ACCeler94 commented on src/components/common/ProductBox/ProductBox.js
> +          <Button variant='outline' onClick={() => onAddToCompare(id, imgSrc)}>
please use event.preventDefault() to stop the page from jumping to the top when clicking the button

2023-08-11 11:31 UTC, ACCeler94 commented on src/components/common/ProductBox/ProductBox.js
> +    dispatch(addProductToCompare({ id, imgSrc }));
for discussion: in my opinion it would be better and future proof to add the whole product object (with all it's properties like name, price, stars etc.) to the comparableProducts state. Later it will allow to implement comparing functionality without any changes here.

2023-08-15 14:45 UTC, Adriannan23 commented on src/components/common/ProductBox/ProductBox.js
> +          <Button variant='outline' onClick={() => onAddToCompare(id, imgSrc)}>
done :) thank you!

2023-08-15 15:02 UTC, ACCeler94 approved these changes

2023-08-15 15:02 UTC, merged