Task-21
odevpl/wdp-2308 pull request #22
Opened 2023-08-11 15:23 UTC by ACCeler94

Add functionality to rate products by user

2023-08-13 17:05 UTC, HSgod requested changes

2023-08-13 17:05 UTC, HSgod commented on src/redux/initialState.js
> +      userRating: 0,
Do we need it here if it doesn't do anything?

2023-08-14 20:13 UTC, ACCeler94 commented on src/redux/initialState.js
> +      userRating: 0,
Yeah, I forgot to delete that. Thanks!

2023-08-14 22:40 UTC, HSgod approved these changes

2023-08-14 22:40 UTC, merged